spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    jdbc-url: ENC(KEopqKdbpxU95+zpFTe4BkMTC9ZdssJ9xNxKWSKrrh34jfiUR/TM7BkbFbiC63R0bzHTnGbJjcE=)
    username: ENC(BH/64B+Su8+cDVObzGV8PA==)
    password: ENC(jD+7CTw8oRhHV1GmluohTMhft90W+EP6)
    hikari:
      connection-timeout: 5000
      validation-timeout: 1000
      maximum-pool-size: 30
      minimum-idle: 2

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    # LIV
    password: ZnNzd21zTGl2S2V5IzA5MDZmc3N3bXNMaXZLZXkjJCU=


logging:
  pattern:
    console: "[LIV] [%d{yyyy-MM-dd HH:mm:ss.SSS}] [%-5level] [%logger.%method:line-%line] - %msg%n"

sweettracker.url: http://trace-api.sweettracker.net
sweet:
  callback_url:
  callback_type: json
  type: json
  tier:
  key: