spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    jdbc-url: ENC(KlSqGkHe83WpeVcuHevPYkZZYuTRXmvapPndd3m0Zf+Dau5oeHlEPKpHB1hI/iLOjFcrZWyh8cVXJiULxLykpg==)
    username: ENC(ZURfTb9YJ6F7RMYvEZbqKA==)
    password: ENC(WvtAGVt59Exf3yv9mA1iCk6ksCSeGYvC)
    hikari:
      connection-timeout: 5000
      validation-timeout: 1000
      maximum-pool-size: 30
      minimum-idle: 2

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    # STG
    password: ZnNzd21zd21zMTIzNDU2Nzg5MGFiY2RlZmZzc3dtczI=

logging:
  pattern:
    console: "[STG] [%d{yyyy-MM-dd HH:mm:ss.SSS}] [%-5level] [%logger.%method:line-%line] - %msg%n"


sweettracker.url: http://trace-api-dev.sweettracker.net:8102
sweet:
  callback_url: http://49.1.133.140:8080/invoice/callback
  callback_type: json
  type: json
  tier: testuser
  key: testuser
