api.url: http://localhost:8080
# api.url: http://trace-api-dev.sweettracker.net:8102

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://{host}?serverTimezone=UTC&characterEncoding=UTF-8
    username: username
    password: password

#path 보다 name 우선
logging:
  file:
    name: logs/apiSample.log
    #path: /Users/hw/Desktop/logs/
  level:
    root: info
    # sample.apiTest: debug 원하는 패키지 로그레벨 따로 지정가능


