greeting:
  message: this is main application-local.yaml

spring:
  datasource:
    hikari:
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      jdbc-url: ENC(y12ZRP6IUflST0DJJZW5KHNHD1pleOOXxjhU9BLxDYR0bQxWXf2NtShdEEX5Kuix0gMh04z2VKXxEyl8v/gDNQ==)
      username: ENC(6M6IbMJQVkVuuQU8XCa9XQ==)
      password: ENC(TKMJVjS1KBeDLg4wxoYm2kI9y4NKQFbI)
      max-lifetime: 50000 #default 30분(1800000 ms) < mysql wait_timeout (default: 28800) 8시간보다 2~3초 짧게
      connection-timeout: 30000 #default 30초
      validation-timeout: 5000 #default 5초
      maximum-pool-size: 1
      connection-test-query: SELECT 1

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    #LOCAL
    password: ZnNzd21zMTIzNDU2Nzg5MGZzc3dtczEyMzQ1Njc4OTA=

opinet:
  key: F230623166
  url: http://www.opinet.co.kr/api
  out: json

slack:
  webhook:
    url: https://hooks.slack.com/services/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